version: '3'

networks:
  chat-net:
    driver: bridge

services:
  nginx-api-proxy:
    image: nginx:latest
    container_name: nginx-api-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/api-proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/api-proxy/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/api-proxy/log:/var/log/nginx
  # extra_hosts: # linux
  #  - "host.docker.internal:host-gateway"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmx
    volumes:
      - ./redis/data:/data
      #- ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  mysql_primary:
    image: mysql:8.0.28
    container_name: mysql_primary
    restart: always
    command: >
      bash -c "chmod 644 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"
    volumes:
      - ./mysql/primary/data:/var/lib/mysql
      - ./mysql/primary/conf:/etc/mysql/conf.d
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=P@ssW0rd!@#
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    networks:
      - chat-net

  mysql_replica:
    container_name: mysql_replica
    image: mysql:8.0.28
    restart: always
    depends_on:
      - mysql_primary
    command: >
      bash -c "chmod 644 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"
    volumes:
      - ./mysql/replica/data:/var/lib/mysql
      - ./mysql/replica/conf:/etc/mysql/conf.d
    environment:
      - TZ=UTC
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=P@ssW0rd!@#
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3307:3306"
    networks:
      - chat-net

