package xyz.jocn.chat.common.enums;

public enum ResourceType {
	USER,
	ROOM, ROOM_MESSAGE, ROOM_PARTICIPANT,
	THREAD, THREAD_MESSAGE, THREAD_PARTICIPANT, THREAD_MESSAGE_MARK,
	FRIEND, FRIEND_BLOCK
}
