package xyz.jocn.chat.common.exception;

public enum ResourceType {
	USER,
	CHANNEL, CHANNEL_MESSAGE, CHANNEL_PARTICIPANT, CHANNEL_MESSAGE_REACTION,
	THREAD, THREAD_MESSAGE, THREAD_PARTICIPANT, THREAD_MESSAGE_REACTION,
	FRIEND, FRIEND_BLOCK,
	FILE
}
