package xyz.jocn.chat.common.exception;

public enum ResourceType {
	USER,
	ROOM, ROOM_MESSAGE, ROOM_PARTICIPANT, ROOM_MESSAGE_REACTION,
	THREAD, THREAD_MESSAGE, THREAD_PARTICIPANT, THREAD_MESSAGE_REACTION,
	FRIEND, FRIEND_BLOCK,
	FILE
}
